all: clean test zad2 zad3 zad4 zad5 zad6
clean:
	rm -rf *.out
test:
	gcc test.c -fopenmp -o test.out
zad2:
	gcc zad2.c -fopenmp -lm -o zad2.out
zad3:
	gcc zad3.c -fopenmp -lm -o zad3.out
zad4:
	gcc zad4.c -fopenmp -lm -o zad4.out
zad5:
	gcc zad5.c -fopenmp -lm -o zad5.out
zad6:
	gcc zad6.c -fopenmp -lm -o zad6.out
